_base_: [
  'configs/datasets/imagenet/imagenet.yaml',
]

model:
  name: 'resnet18'
  pretrained: True

runner:
  name: 'qat'
  verbose: True

quant:
  default:
    weight:
      n_bits: 8
      symmetric: True
      signed: True
      granularity: 'layer'
      range:
        name: 'mse'
        maxshrink: 0.8
        grid: 100
    activation:
      n_bits: 32
      range:
        name: 'minmax'
    bn_folding: True

train_dataset:
  num_shots: 16

train_loader:
  batch_size: 128

optimizer:
  name: 'adam'
  lr: 1e-5

lr_scheduler:
  name: 'constant'

train:
  calibrated_epoch: 1
  max_epoch: 20
  print_freq: 10
  eval_freq: 1

gpus: 0
use_cude: True

seed: 1
output_dir: 'results/qat/weight_quantize/mse_layer/resnet18/W8/seed1'
