model:
  name: 'resnet18'
  pretrained: True

runner:
  name: 'qat'
  verbose: True

train_dataset:
  num_shots: 16

train_loader:
  batch_size: 128

train:
  calibrated_epoch: 1
  max_epoch: 20
  print_freq: 10
