_base_: [
  'configs/datasets/imagenet/imagenet.yaml',
]

model:
  name: 'resnet18'
  pretrained: True

runner:
  name: 'ptq'
  verbose: True

quant:
  default:
    weight:
      n_bits: 32
      range:
        name: 'minmax'
    activation:
      n_bits: 8
      symmetric: False
      granularity: 'channel'
      range:
        name: 'aciq'
        fuse_relu: True
    bn_folding: True

  /conv1:
    activation:
      range:
        name: 'minmax'

train_dataset:
  num_shots: 16

train_loader:
  batch_size: 128

train:
  max_epoch: 1
  print_freq: 10

gpus: 0
use_cude: True

seed: 1
output_dir: 'results/ptq/activation_quantize/aciq_channel/resnet18/A8/seed1'
