_base_: [
  'configs/datasets/imagenet/imagenet.yaml',
]

model:
  name: 'resnet18'
  pretrained: True

runner:
  name: 'qat'
  verbose: True

quant:
  default:
    weight:
      n_bits: 8
      symmetric: True
      signed: True
      granularity: 'channel'
      range:
        name: 'minmax'
        percentile: 0.0
    activation:
      n_bits: 32
      range:
        name: 'minmax'
    bn_folding: True
    bias_correct:
      momentum: 0.1

train_dataset:
  num_shots: 16

train_loader:
  batch_size: 128

optimizer:
  name: 'adam'
  lr: 1e-5

lr_scheduler:
  name: 'constant'

train:
  calibrated_epoch: 1
  max_epoch: 20
  print_freq: 10
  eval_freq: 1

gpus: 0
use_cude: True

seed: 1
output_dir: 'results/qat/bias_correct/minmax_channel/resnet18/W8/seed1'
