_base_: [
  'configs/datasets/imagenet/imagenet.yaml',
  'configs/runners/ptq/base.yaml',
  'configs/runners/ptq/mse/base.yaml',
]

model:
  name: 'resnet18'
  pretrained: True

quant:
  default:
    weight:
      n_bits: 6
      symmetric: True
      granularity: 'channel'
    activation:
      n_bits: 6
    bn_folding: True

train_dataset:
  num_shots: 16

gpus: 0
use_cuda: True

seed: 1
output_dir: 'results/ptq/mse/ptq_rn18_w6a6_bnf_sym_chan_in1k_16shots/seed1'
