_base_: configs/datasets/dataloader.yaml

train_dataset:
  name: 'imagenet'
  root: '/datasets/ImageNet'
  split: 'train'
  
  transform:
    random_resized_crop:
      size: 224
      scale: [0.7, 1.0]
    random_horizontal_flip:
      p: 0.5
    to_tensor: null
    normalize: 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  name: 'imagenet'
  root: '/datasets/ImageNet'
  split: 'val'

  transform:
    resize:
      size: 256
    center_crop:
      size: 224
    to_tensor: null
    normalize: 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

test_dataset:
  name: 'imagenet'
  root: '/datasets/ImageNet'
  split: 'val'

  transform:
    resize:
      size: 256
    center_crop:
      size: 224
    to_tensor: null
    normalize: 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
