_base_: ./configs/datasets/dataloader.yaml

test_dataset:
  name: 'imagenet_c'
  root: '/datasets/ImageNet-C'
  corruption: 'gaussian_noise'
  level: 1

  transform:
    resize:
      size: 256
    center_crop:
      size: 224
    to_tensor: null
    normalize: 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
