quant:
  default:
    weight:
      n_bits: 8
      symmetric: True
      signed: True
      granularity: 'channel'
      range:
        name: 'mse'
        percentile: 0.0
        maxshrink: 0.8
        grid: 100
        norm: 2
    activation:
      n_bits: 8
      symmetric: False
      granularity: 'layer'
      range:
        name: 'maminmax'
        percentile: 0.0
        momentum: 0.1
    bn_folding: True
  
  nn_linear:
    activation:
      range:
        name: 'cross_entropy'
        percentile: 0.0
        momentum: 0.1
        maxshrink: 0.8
        grid: 100
