quant:
  default:
    weight:
      n_bits: 8
      symmetric: True
      signed: True
      granularity: 'channel'
      range:
        name: 'minmax'
        percentile: 0.0
    activation:
      n_bits: 8
      symmetric: False
      granularity: 'layer'
      range:
        name: 'maminmax'
        percentile: 0.0
        momentum: 0.1
    bn_folding: True
