_base_: [
  'configs/datasets/imagenet/imagenet.yaml',
  'configs/runners/ptq/base.yaml',
  'configs/runners/ptq/minmax/base.yaml',
]

model:
  name: 'resnet18'
  pretrained: True

quant:
  default:
    weight:
      n_bits: 8
      symmetric: True
      granularity: 'channel'
    activation:
      n_bits: 8
    bn_folding: True

train_dataset:
  num_shots: 16

gpus: 0
use_cuda: True

seed: 1
output_dir: 'results/ptq/minmax/ptq_rn18_w8a8_bnf_sym_chan_in1k_16shots/seed1'
